format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

project_type: other

workflows:
  primary:
    steps:
      - activate-ssh-key@4:
          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
      - git-clone@8: {}

      - cache-pull@2: {}

      - npm@1:
          inputs:
            - command: install

      - script@1:
          title: "Capacitor Sync"
          inputs:
            - content: |
                #!/bin/bash
                npx cap sync ios

      - cocoapods-install@2: {}

      # Install your manually uploaded signing certs & profiles
      - certificate-and-profile-installer@1: {}

      - xcode-archive@4:
          inputs:
            - project_path: "ios/App/App.xcworkspace"
            - scheme: "App"
            - configuration: "Release"
            - export_method: "app-store"
            - export_options_plist_content: |
                <?xml version="1.0" encoding="UTF-8"?>
                <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
                <plist version="1.0">
                <dict>
                    <key>method</key>
                    <string>app-store</string>
                    <key>teamID</key>
                    <string>X3L24943PL</string>
                    <key>signingCertificate</key>
                    <string>Apple Distribution</string>
                    <key>provisioningProfiles</key>
                    <dict>
                        <key>com.treasurefitness.com</key>
                        <string>tfit_bitrise_provision</string>
                    </dict>
                </dict>
                </plist>

      - deploy-to-itunesconnect-deliver@2:
          inputs:
            - ipa_path: "$BITRISE_IPA_PATH"
            - submit_for_review: "no"

      - deploy-to-bitrise-io@2: {}

      - cache-push@2: {}

triggers:
  - push_branch: master
    workflow: primary
  - pull_request_source_branch: "*"
    workflow: primary

meta:
  bitrise.io:
    stack: osx-xcode-16.0.x
    machine_type_id: g2.mac.large
