format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

project_type: other

workflows:
  primary:
    steps:
      - activate-ssh-key@4:
          run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
      - git-clone@8: {}

      # Optional: Pull caches to speed up builds
      - cache-pull@2: {}

      # Install Node modules for Capacitor/Ionic
      - npm@1:
          inputs:
            - command: install

      # Run Capacitor sync to update native iOS project
      - script@1:
          title: "Capacitor Sync"
          inputs:
            - content: |
                #!/bin/bash
                npx cap sync ios

      # Install CocoaPods for native deps
      - cocoapods-install@2: {}

      # Install signing certs and provisioning profiles
      - certificate-and-profile-installer@1: {}

      # NEW: Manage iOS Code Signing (replaces deprecated auto-provision step)
      - manage-ios-code-signing@1:
          inputs:
            - distribution_method: "app-store"
            - project_path: "ios/App.xcworkspace"
            - scheme: "app"

      # Archive & export signed .ipa for App Store Connect
      - xcode-archive@4:
          inputs:
            - project_path: "ios/App.xcworkspace"
            - scheme: "app"
            - configuration: "Release"
            - export_method: "app-store"

      # Upload to App Store Connect automatically
      - deploy-to-itunesconnect-deliver@2:
          inputs:
            - ipa_path: "$BITRISE_IPA_PATH"
            - submit_for_review: "no"

      # Upload artifacts to Bitrise too
      - deploy-to-bitrise-io@2: {}

      # Optional: Push caches
      - cache-push@2: {}

triggers:
  - push_branch: master
    workflow: primary
  - pull_request_source_branch: "*"
    workflow: primary

meta:
  bitrise.io:
    stack: osx-xcode-16.0.x
    machine_type_id: g2.mac.large
