workflows:
  ios-capacitor-dev:
    name: iOS Build (signed)
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
      groups:
        - firebase
        - kajabi
        - signing
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL" 
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync
        script: |
          npx cap sync ios
          npx cap copy ios
          gem install cocoapods
          cd ios/App && pod install

      - name: Build iOS app (signed)
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --export-method app-store \
            --team-id X3L24943PL

    artifacts:
      - build/ios/ipa/*.ipa
