workflows:
  ios-capacitor-testflight:
    name: iOS TestFlight Build
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL" 
        BUNDLE_ID: "com.treasurefitness.com"
      groups:
        - firebase
    integrations:
      app_store_connect: admin_key

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync and Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Set Development Team in Xcode project
        script: |
          # This sed command is still fine as it sets the team ID directly in the pbxproj
          XCODE_PROJECT="ios/App/App.xcodeproj/project.pbxproj"
          sed -i.bak "s/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM};/g" $XCODE_PROJECT

      - name: Automatic Code Signing Setup
        script: |
          # Initialize keychain
          keychain initialize

          # Fetch or create signing files using App Store Connect API
          # --type IOS_APP_STORE is for TestFlight/App Store Distribution
          # --create will create if missing
          app-store-connect fetch-signing-files "${BUNDLE_ID}" --type IOS_APP_STORE --create

          # Apply fetched profiles to the Xcode project
          # This command automatically updates Xcode's signing settings
          xcode-project use-profiles

      - name: Build and export iOS app
        script: |
          # Ensure we are in the correct directory for xcodebuild
          # The archive path needs to be absolute or relative from the project root.
          # Let's keep it relative to the Codemagic build root for consistency.
          # The default archive path for xcodebuild is often within DerivedData,
          # but we can specify a common one to make it explicit.
          XCARCHIVE_PATH="${CM_BUILD_DIR}/App.xcarchive"

          echo "Archiving project..."
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "${XCARCHIVE_PATH}" \
            archive || exit 1 # Exit on archive failure

          echo "Exporting IPA using Codemagic CLI..."
          # cd back to the project root or use absolute paths for xcode-project
          cd "${CM_BUILD_DIR}" # Ensure we are in the root directory where `App.xcarchive` is if created there.

          xcode-project build-ipa \
            --archive-path "${XCARCHIVE_PATH}" \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --ipa-directory build/ios/ipa # Specify output directory for IPA. Default is build/ios/ipa

          # The artifacts section will then pick up from build/ios/ipa/*.ipa

    artifacts:
      - build/**/*.ipa