workflows:
  ios-manual-signing:
    name: iOS Manual Signing Build
    environment:
      xcode: latest
      groups:
        - firebase

    integrations:
      app_store_connect: App Store API

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync & Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Setup keychain & manual signing
        script: |
          # Initialize keychain
          keychain initialize

          # Import uploaded .p12 and provisioning profile
          keychain add-certificates

          # Attach provisioning profile
          app-store-connect fetch-signing-files "com.treasurefitness.com" --type IOS_APP_STORE --create || true

          cd ios/App

          echo "Forcing CODE_SIGN_STYLE to Manual..."
          xcode-project update-build-settings \
            --target App \
            --configuration Release \
            --setting CODE_SIGN_STYLE=Manual \
            --setting DEVELOPMENT_TEAM="X3L24943PL" \
            App.xcodeproj

          xcode-project use-profiles

          cd ../..

      - name: Archive and export IPA
        script: |
          XCARCHIVE_PATH="${CM_BUILD_DIR}/App.xcarchive"

          echo "Archiving project..."
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "${XCARCHIVE_PATH}" \
            DEVELOPMENT_TEAM="X3L24943PL" \
            archive || exit 1

          echo "Exporting IPA with ExportOptions.plist..."
          xcodebuild -exportArchive \
            -archivePath "${XCARCHIVE_PATH}" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "${CM_BUILD_DIR}/build/ios/ipa"

    artifacts:
      - build/ios/ipa/*.ipa