workflows:
  ios-capacitor-testflight:
    name: iOS TestFlight Build
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL" 
        BUNDLE_ID: "com.treasurefitness.com"
      groups:
        - firebase
    integrations:
      app_store_connect: admin_key

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync and Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Automatic Code Signing Setup
        script: |
          keychain initialize

          # Fetch or create signing files. This also implicitly configures the development team.
          app-store-connect fetch-signing-files "${BUNDLE_ID}" --type IOS_APP_STORE --create

          # Use profiles. This step should properly apply the development team and signing settings.
          # We provide the workspace and scheme explicitly here to ensure it's targeting the right project.
          xcode-project use-profiles \
            --workspace ios/App/App.xcworkspace \
            --scheme App

      - name: Build and export iOS app
        script: |
          XCARCHIVE_PATH="${CM_BUILD_DIR}/App.xcarchive"

          echo "Archiving project..."
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "${XCARCHIVE_PATH}" \
            archive || exit 1

          echo "Exporting IPA using Codemagic CLI..."
          cd "${CM_BUILD_DIR}" # Ensure we are in the root directory for xcode-project build-ipa

          xcode-project build-ipa \
            --archive-path "${XCARCHIVE_PATH}" \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --ipa-directory build/ios/ipa

    artifacts:
      - build/**/*.ipa