workflows:
  ios-manual-signing:
    name: iOS Manual Signing Build
    environment:
      xcode: latest
    certificates:
      - TTC_cert
    provisioning_profiles:
      - Tfit provision
    vars:
      BUNDLE_ID: "com.treasurefitness.com"
      DEVELOPMENT_TEAM: "X3L24943PL"

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync & Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Setup keychain & manual signing
        script: |
          keychain initialize

          echo "Fetching uploaded signing files..."
          app-store-connect fetch-signing-files "${BUNDLE_ID}" --type IOS_APP_STORE

          cd ios/App

          echo "Forcing CODE_SIGN_STYLE to Manual..."
          xcode-project update-build-settings \
            --target App \
            --configuration Release \
            --setting CODE_SIGN_STYLE=Manual \
            --setting DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
            App.xcodeproj

          echo "Attaching uploaded provisioning profile..."
          xcode-project use-profiles

          cd ../..

      - name: Archive and export IPA
        script: |
          XCARCHIVE_PATH="${CM_BUILD_DIR}/App.xcarchive"

          echo "Archiving project..."
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "${XCARCHIVE_PATH}" \
            DEVELOPMENT_TEAM="${DEVELOPMENT_TEAM}" \
            archive || exit 1

          echo "Exporting IPA..."
          cd "${CM_BUILD_DIR}"
          xcode-project build-ipa \
            --archive-path "${XCARCHIVE_PATH}" \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --ipa-directory build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
