workflows:
  ios-capacitor-dev:
    name: iOS Build (No Signing Yet)
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
    working_directory: Tfit-app
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing node modules..."
          npm ci || { echo "npm ci failed"; exit 1; }
      
          echo "Running build..."
          npm run build || { echo "Build failed"; exit 1; }

      - name: Capacitor Sync
        script: |
          npx cap sync ios
          npx cap copy ios
          cd ios/App && pod install

      - name: Build iOS app (unsigned)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     archive

          # Export the archive as unsigned .ipa
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     -exportPath $CM_BUILD_DIR/build \
                     -exportOptionsPlist ExportOptions.plist || echo "Skipping code signing"

    artifacts:
      - build/**/*.ipa
      - ios/App/build/**/*.app
