workflows:
  ios-automatic-signing:
    name: iOS Automatic Signing Build
    environment:
      xcode: latest
      groups:
        - firebase
      ios_signing:
        distribution_type: app-store
        bundle_identifier: com.treasurefitness.com

    integrations:
      app_store_connect: App Store API 

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync & Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Build and export IPA
        script: |
          set -x
          
          XCARCHIVE_PATH="${CM_BUILD_DIR}/App.xcarchive"
          
          # Let Codemagic handle all the signing automatically
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "${XCARCHIVE_PATH}" \
            -allowProvisioningUpdates \
            archive

          xcodebuild -exportArchive \
            -archivePath "${XCARCHIVE_PATH}" \
            -exportPath "${CM_BUILD_DIR}/build/ios/ipa" \
            -exportOptionsPlist "ExportOptions.plist"   

    artifacts:
      - build/ios/ipa/*.ipa 
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM