workflows:
  ios-capacitor-testflight:
    name: iOS TestFlight Build
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL" 
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync
        script: |
          npx cap sync ios
          npx cap copy ios
          gem install cocoapods
          cd ios/App && pod install

      - name: Build iOS app (signed)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     CODE_SIGN_STYLE=Manual \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     PROVISIONING_PROFILE_SPECIFIER="Your Provisioning Profile Name" \
                     archive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     -exportPath $CM_BUILD_DIR/build \
                     -exportOptionsPlist $CM_BUILD_DIR/ExportOptions.plist
    artifacts:
      - build/**/*.ipa
    signing:
      provisioning_profile: tfitapp.mobileprovision
      certificate: tfit_cert.p12
