workflows:
  ios-capacitor-testflight:
    name: iOS TestFlight Build
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL"
        # Make sure your bundle ID is also a variable for consistency
        BUNDLE_ID: "com.treasurefitness.com"
      groups:
        - firebase
      ios_signing:
        distribution_type: app_store 
        bundle_identifier: com.treasurefitness.com

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync and Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Set Development Team in Xcode project
        script: |
          # This is the crucial step to fix the "requires a development team" error.
          # It directly modifies the project file to insert your team ID.
          XCODE_PROJECT="ios/App/App.xcodeproj/project.pbxproj"
          sed -i.bak "s/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM};/g" $XCODE_PROJECT

      - name: Initialize keychain and set up profiles
        script: |
          keychain initialize
          # This command uses the ios_signing section to set the correct provisioning profiles
          xcode-project use-profiles

      - name: Build and export iOS app
        script: |
          # Navigate to the ios directory
          cd ios/App

          # Create a dynamic ExportOptions.plist for the export step
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string> 
              <key>teamID</key>
              <string>${DEVELOPMENT_TEAM}</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>uploadBitcode</key>
              <true/>
              <key>compileBitcode</key>
              <true/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>${BUNDLE_ID}</key>
                  <string>${CM_PROVISIONING_PROFILE_UUID}</string>
              </dict>
              <key>signingCertificate</key>
              <string>${CM_CERTIFICATE_COMMON_NAME}</string>
          </dict>
          </plist>
          EOF

          echo "Generated ExportOptions.plist:"
          cat ExportOptions.plist

          # Build the archive
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath App.xcarchive \
            archive

          # Export the archive to an .ipa file
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportPath ../../build \
            -exportOptionsPlist ExportOptions.plist

    artifacts:
      - build/**/*.ipa