workflows:
  ios-capacitor-signed:
    name: iOS Build (Signed)
    environment:
      vars:
        XCODE_WORKSPACE: App.xcworkspace
        XCODE_SCHEME: App
      node: 22.15.0
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.treasurefitness.com
        team_id: X3L24943PL
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync
        script: |
          npx cap sync ios
          npx cap copy ios
          cd ios/App && pod install

      - name: Build iOS app (signed)
        script: |
          cd ios/App
          xcodebuild -workspace $XCODE_WORKSPACE \
                     -scheme $XCODE_SCHEME \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     archive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     -exportPath $CM_BUILD_DIR/build \
                     -exportOptionsPlist ExportOptions.plist

    artifacts:
      - build/**/*.ipa
