workflows:
  ios-capacitor-testflight:
    name: iOS TestFlight Build
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL"
        BUNDLE_ID: "com.treasurefitness.com"
      groups:
        - firebase
    ios_signing:
      provisioning_profiles:
        - Tfit provision
      certificates:
        - tfit_cert

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync and Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Set Development Team in Xcode project
        script: |
          # This command fixes the "requires a development team" error during the archive step.
          XCODE_PROJECT="ios/App/App.xcodeproj/project.pbxproj"
          sed -i.bak "s/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM};/g" $XCODE_PROJECT

      - name: Initialize keychain and set up profiles
        script: |
          keychain initialize
          xcode-project use-profiles

      - name: Build and export iOS app
        script: |
          cd ios/App

          # This script creates the ExportOptions.plist needed for the export step.
          # It uses the certificate's official Common Name, which is the most reliable method.
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string> 
              <key>teamID</key>
              <string>${DEVELOPMENT_TEAM}</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>uploadBitcode</key>
              <true/>
              <key>compileBitcode</key>
              <true/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>${BUNDLE_ID}</key>
                  <string>${CM_PROVISIONING_PROFILE_UUID}</string>
              </dict>
              <key>signingCertificate</key>
              <string>Apple Distribution: Roseanne Kamau (X3L24943PL)</string>
          </dict>
          </plist>
          EOF

          echo "--- Generated ExportOptions.plist ---"
          cat ExportOptions.plist
          echo "------------------------------------"

          # Build the archive
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath App.xcarchive \
            archive

          # Export the archive to an .ipa file
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportPath ../../build \
            -exportOptionsPlist ExportOptions.plist

    artifacts:
      - build/**/*.ipa