workflows:
  ios-capacitor-testflight:
    name: iOS TestFlight Build
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL" 
        BUNDLE_ID: "com.treasurefitness.com"
      groups:
        - firebase 
    integrations:
      app_store_connect: Codemagic app manager

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync and Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Automatic Code Signing Setup
        script: |
          keychain initialize

          app-store-connect fetch-signing-files "${BUNDLE_ID}" --type IOS_APP_STORE --create

          # Change to the iOS project directory
          cd ios/App

          # Use profiles AND explicitly set the DEVELOPMENT_TEAM for the target
          # This ensures the project knows which team to associate with the signing.
          xcode-project use-profiles \
            --set-development-team "${DEVELOPMENT_TEAM}" \
            --project "App.xcodeproj" # Explicitly target your .xcodeproj

          # Change back to the root directory
          cd ../..

      - name: Build and export iOS app
        script: |
          XCARCHIVE_PATH="${CM_BUILD_DIR}/App.xcarchive"

          echo "Archiving project..."
          # xcodebuild will now use the signing identities applied by xcode-project use-profiles
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "${XCARCHIVE_PATH}" \
            archive || exit 1

          echo "Exporting IPA using Codemagic CLI..."
          # Ensure we are in the root directory for xcode-project build-ipa if needed,
          # or adjust paths if it expects to be in the ios/App directory.
          # CM_BUILD_DIR is the root of your cloned repository.
          cd "${CM_BUILD_DIR}" 

          xcode-project build-ipa \
            --archive-path "${XCARCHIVE_PATH}" \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --ipa-directory build/ios/ipa

    artifacts:
      - build/**/*.ipa