workflows:
  ios-capacitor-testflight:
    name: iOS TestFlight Build
    environment:
      node: 22.15.0
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL"
      groups:
        - firebase
      ios_signing:
        distribution_type: app_store 
        bundle_identifier: com.treasurefitness.com

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync
        script: |
          npx cap sync ios
          npx cap copy ios
          gem install cocoapods
          cd ios/App/App && pod install

      - name: Initialize keychain
        script: keychain initialize
        
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: Build iOS app (signed)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath App.xcarchive \
            archive
      
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportPath $CM_BUILD_DIR/build \
            -exportOptionsPlist ExportOptions.plist


    artifacts:
      - build/**/*.ipa
