workflows:
  ios-manual-signing:
    name: iOS Manual Signing Build
    environment:
      xcode: latest
      groups:
        - firebase
      vars:
        BUNDLE_ID: "com.treasurefitness.com"
        APPLE_DEVELOPER_TEAM_ID: "X3L24943PL"
        
    integrations:
      app_store_connect: App Store API

    scripts:
      - name: Set up provisioning profiles
        script: |
          # Download and install certificates and provisioning profiles
          # This assumes you've uploaded them to Codemagic
          echo "Setting up code signing..."
          
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync & Pod Install
        script: |
          npx cap sync ios
          cd ios/App && pod install

      - name: Build and export IPA
        script: |
          set -x
          
          XCARCHIVE_PATH="${CM_BUILD_DIR}/App.xcarchive"
          
          # Manual code signing
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "${XCARCHIVE_PATH}" \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="YourProvisioningProfileName" \
            DEVELOPMENT_TEAM="${APPLE_DEVELOPER_TEAM_ID}" \
            archive

          xcodebuild -exportArchive \
            -archivePath "${XCARCHIVE_PATH}" \
            -exportPath "${CM_BUILD_DIR}/build/ios/ipa" \
            -exportOptionsPlist "ExportOptions.plist"

    artifacts:
      - build/ios/ipa/*.ipa