workflows:
  ios-capacitor-testflight:
    name: iOS TestFlight Build
    environment:
      node: 22.15.0
      xcode: 15.3 
      cocoapods: default
      groups:
        - signing
        - firebase 
      vars:
        DEVELOPMENT_TEAM: "X3L24943PL"
        BUNDLE_ID: "com.treasurefitness.com"

    code_signing:
      provisioning_profiles:
        - tfitapp.mobileprovision 
      certificates:
        - tfit_cert.p12

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm run build

      - name: Capacitor Sync
        script: |
          npx cap sync ios
          # 'cap sync' already does the copy, so 'cap copy' is redundant
          cd ios/App && pod install && cd ../..

      - name: Set up code signing
        script: |
          keychain initialize
          # Use the password from the 'signing' environment group
          keychain add-certificates --certificate-password $CM_CERTIFICATE_PASSWORD
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          # Find the profile Codemagic downloaded and copy it to where Xcode can find it
          PROFILE_PATH=$(find $CM_BUILD_DIR/profiles -name "*.mobileprovision")
          cp "$PROFILE_PATH" "$PROFILES_HOME"

      - name: Build iOS app (signed)
        script: |
          cd ios/App
          # Get the UUID from the profile file dynamically
          PROFILE_UUID=$(grep UUID -A1 -a "$PROFILE_PATH" | grep -io "[-A-F0-9]\{36\}")

          xcodebuild -workspace App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     CODE_SIGN_STYLE=Manual \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     CODE_SIGN_IDENTITY="Apple Distribution" \
                     PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
                     archive

          # Use the correct relative path to the plist you committed
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/App.xcarchive \
                     -exportPath $CM_BUILD_DIR/build \
                     -exportOptionsPlist ExportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/build/*.ipa
      - $CM_BUILD_DIR/build/*.dSYM